/*
 * Chat API for LINE Incubation Program (Solution Engineer)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Body struct {

	User string `json:"user"`

	Message string `json:"message"`
}
